apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: ghcr.io/minbzk/bureaublad-api:v1.0.0
          imagePullPolicy: Always
          name: bureaublad-api
          env:
            - name: AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sec-bureaublad-backend
                  key: AI_API_KEY
            - name: AI_BASE_URL
              value: "https://api.ssc-ict-trial.ubiops.io/v2.1/projects/external-poc/openai-compatible/v1"
            - name: AI_MODEL
              value: "ubiops-deployment/bzk-openbsw-chat//llama-3.3-70b-instruct-awq"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          ports:
            - containerPort: 8080
              protocol: TCP
